### ISSUE TITLE
Decide game title

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#1]
This project needs a title!  
I would say to wait till we have some gameplay in-place or a game pitch to assign any title (we will change this repository name, probably). However if you have any idea, feel free to propose it.

**Comment by woody889** [comment]
Iron'n Fire 🧨⚙️

**Comment by ZsTiziano** [comment]
" Enemy Attack "

**Comment by ZsTiziano** [comment]
" Enemy Attack "

**Comment by Khelthos** [comment]
"This war of them"?

**Comment by m0rp30** [comment]
"Destroy armor" or "Tower Destroyer"

**Comment by mRuggi** [comment]
Referring to the [story pitch](https://github.com/crystal-bit/hacktoberfest-2020/issues/13#issuecomment-703652668) the title of this game could be "Defending Todot" a title that could remind people of 'Waiting for Godot'

**Comment by davcri** [comment]
I would say let's set Sunday 25 October as a deadline for this issue and #13.   
So in the last week of October we can focus on polighing the game and implement the missing parts!

Currently I like "Defending Todot" since we have a connection to the game story! However feel free to say your opinion!

**Comment by vittorio-del-bianco** [comment]
I like Defending Todot too.

**Comment by Andrea1141** [comment]
In my opinion "Defending Todot" is nice, but I also suggest "Fighting for Todot"

**Comment by davcri** [comment]
Defending Todot!
