### ISSUE TITLE
Update pause layer style and fonts

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#101]
![image](https://user-images.githubusercontent.com/6860637/97367421-58020880-18a9-11eb-97b7-f884419b090b.png)

Also it would be nice to add the "pressed" sound effect when the links are pressed

**Comment by antocorr** [comment]
<img width="1277" alt="Schermata 2020-10-31 alle 14 21 55" src="https://user-images.githubusercontent.com/1094862/97780369-83744400-1b84-11eb-8ecb-3f037953556d.png">

**Comment by antocorr** [comment]
<img width="1279" alt="Schermata 2020-10-31 alle 17 30 11" src="https://user-images.githubusercontent.com/1094862/97784422-c7744280-1b9e-11eb-9ea7-2e041b1a3ec9.png">
