### ISSUE TITLE
Reopen strategic point menu

### ISSUE THREAD

**Issue by m0rp30** [crystal-bit/hacktoberfest-2020#106]
Only on the sniper tower is possible to reopen strategic point menu.

**Comment by masmartyg** [comment]
> Only on the sniper tower is possible to reopen strategic point menu.

Well, actually the strategic point menu only opens if there are enemies in the range of the tower (see ʻif` on line 24 of strategic-point.gd). This is difficult to see because the range of the towers is low but if you raise the range (> 200 for example) you can see it.

**Comment by davcri** [comment]
@masmartyg thanks for pointing this out! I'll close this issue and I would say that we can continue the discussion in #114
