### ISSUE TITLE
Define turret and troop types

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#11]
1. How many **Turrets** we want to support? 
2. What kind of **Troops** will they spawn?
3. What are the advantages/disadvantages in combat between each **Troop** vs **Enemy**? (see #12)
4. Which stats will the **Troops** have (hp, attack, range, speed, cost)?

Requirements:
  - [x] Update the [game design document](https://github.com/crystal-bit/hacktoberfest-2020/blob/master/docs/gdd.md) with the new information

In Kingdom Rush it seems there are 4 types of **Turrets** that allow to spawn 4 troops.
![image](https://user-images.githubusercontent.com/6860637/94792895-ee8df780-03d9-11eb-99f6-05f84ef97d2f.png)

**Comment by vittorio-del-bianco** [comment]
I'm starting to work on it.
