### ISSUE TITLE
Define Enemy types

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#12]
1. How many **Enemies** we want to support? 
2. Define stats for each Enemy (hp, speed, range, type)

Requirements:
  - [ ] Update the game design document with the new information

Some enemy in Kingdom Rush:

![image](https://user-images.githubusercontent.com/6860637/94793560-f00bef80-03da-11eb-8f5b-fce6d3b881c5.png)
![image](https://user-images.githubusercontent.com/6860637/94793622-09ad3700-03db-11eb-80bf-4155b1d88a65.png)

**Comment by vittorio-del-bianco** [comment]
I'm starting to work on it.
