### ISSUE TITLE
Write a pitch and story for the game

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#13]
Create a short pitch and story setting for the game.

Please keep in mind that probably we are going to use these free assets: https://github.com/crystal-bit/hacktoberfest-2020/tree/master/assets/sprites

Radical changes in the game aesthetic should be discussed with other developers in a separate issue or [on the Discord server](https://discord.com/invite/SA6S2Db).

Requirements:
- [ ] Update the [game design document](https://github.com/crystal-bit/hacktoberfest-2020/blob/master/docs/gdd.md)

**Comment by Khelthos** [comment]
Just a little idea of mine:

_Three nations at war, one battlefield, the prosperous and peaceful land of **Todog**.
The peasants always find themselves in the midst of battles and their precious land ruined!

**BUT NOT ANYMORE!**

The villages of Todog have come together and are joining forces to fight back with fire and iron. 
No invader will dare to disturb this peaceful land again!_

**Comment by davcri** [comment]
I like this @Khelthos! Not sure about how to pronounce Todog however :D Feel free to expand it even more and do a PR!

**Comment by Khelthos** [comment]
I don't know :) I was just playing with the Godot. Could be pronounced like "Too Good"  just for fun and write it like a middle European word 🤣

I'll wait more feedback on that from the others.

I'll try to expand the story description

**Comment by vittorio-del-bianco** [comment]
> Just a little idea of mine:
> 
> _Three nations at war, one battlefield, the prosperous and peaceful land of_ **Todog**_. The peasants always find themselves in the midst of battles and their precious land ruined!_
> 
> **BUT NOT ANYMORE!**
> 
> _The villages of Todog have come together and are joining forces to fight back with fire and iron. No invader will dare to disturb this peaceful land again!_

Is it a fantasy or modern setting? I've just worked on issue 11 and 12 (towers and enemies): I relied on a modern setting, but if you prefer I can adapt to the fantasy (or other, as you wish)... see gdd.

For the land name ... what do you think of Todot?  Pronounced like Godot but starting with T instead of G. :-)

**Comment by Khelthos** [comment]
I like Todot, too 👍 

I was thinking about a modern setting, I already checked the Kenney assets and we could use 3 color variants for the three invader nations and one for the village defenses.

**Comment by davcri** [comment]
Feel free to open the PR @Khelthos, if we need to update the GDD we can do it later also. 

Once we have this in place, we could integrate the story in the game.
Maybe we can spawn some popup text / dialogue at the start of each level?  If you have a specific idea feel free to directly open a new issue!

**Comment by davcri** [comment]
I would say let's set Sunday 25 October as a deadline for this issue and #1.
So in the last week of October we can focus on polishing the game and implement the missing parts!

**Comment by davcri** [comment]
DEFENDING TODOT!
