### ISSUE TITLE
Find a new font

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#14]
Find a font that fits well with the current assets.

**Comment by davcri** [comment]
I'm looking for a font right now

**Comment by davcri** [comment]
What's your favorite? I think we can choose 2 fonts to alternate in the game UI.

1. https://fonts.google.com/specimen/Lemonada?category=Display
2. https://fonts.google.com/specimen/Boogaloo?category=Display#glyphs
3. https://fonts.google.com/specimen/Chewy?category=Display#glyphs
4. https://fonts.google.com/specimen/Luckiest+Guy?category=Display

**Comment by woody889** [comment]
I choose font number 4 luckiest guy! **Very nice**

**Comment by Sop-S** [comment]
I like number 2

**Comment by veonazzo** [comment]
My vote is for **Luckiest Guy (4)**

**Comment by ZsTiziano** [comment]
I agree with you.
I vote **Boogaloo (2)** and **Luckiest Guy (4)**

**Comment by Khelthos** [comment]
Boogaloo

**Comment by davcri** [comment]
Excellent we have some winner :D I'm going to do the PR in a bit. Thanks everyone for the help!
