### ISSUE TITLE
Improve Level 1 aesthetic

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#15]
Currently level1 layout is fine, but it can be improved by placing some graphic element in the scene (maybe also slightly animated to simulate a wind effect).

- [ ] Add grass, trees, improve tiles

If you want to create new level tiles, feel free to open a new issue.

The current state of Level1 (at the time of writing) is:
![image](https://user-images.githubusercontent.com/6860637/94862646-91299300-0439-11eb-9580-87f46946b9d2.png)

**Comment by Karbb** [comment]
I'm gonna make that scene so beautiful that you're all gonna say "MAMMA MIA"
