### ISSUE TITLE
Add credits button to the main menu

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#18]
I implemented the credits scene in #2, now we need to add a button the main menu in order to load the credits scene.

Requirements:

- [ ] Create a new _"Credits"_ button in the main menu
- [ ] Load the credits scene
- [ ] Remember to add yourself to the contributors list in the `credits.gd` script!
- [ ] Once the credits are finished, make the game return to the main menu

**Comment by veonazzo** [comment]
"This issue of mine"

**Comment by davcri** [comment]
Pain of salvation? https://www.youtube.com/watch?v=hiMkUWbmfOg :stuck_out_tongue:

**Comment by veonazzo** [comment]
> Pain of salvation? https://www.youtube.com/watch?v=hiMkUWbmfOg stuck_out_tongue

In realtà stavo pensando più al [https://it.wikipedia.org/wiki/This_War_of_Mine]videogioco(url) ma ho apprezzato molto lo riscoprire una canzone ormai perduta nella memoria... grazie! :+1: 

ps: arriva la PR
