### ISSUE TITLE
Create Tower scene

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#19]
After #11, create a Turret scene.  

The Turret will be created on `StrategicPointMenu` `tower_selected` signal defined in #7. 

Requirements: 
- [ ] A Sprite node. Ideally the Tower will set the Sprite texture depending on its type (probably sent via the `tower_selected` signal)

Things to keep in mind (we still need to clearly define the design of the towers):

- [ ] Some tower types may use a Rally point to deploy troops
- [ ] Some tower types may have a range attack

Implementation is open to discuss.

**Comment by Karbb** [comment]
![Uploading IMG_20201005_141050.jpg…]()
