### ISSUE TITLE
Create level selection scene

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#20]
You have freedom to experiment different layouts. The basic requirement is to have the possibility to load levels defined in `scenes/gameplay/levels/`.

The "Start" button on main menu should load this level selection scene.

#### Future work

- implement level completed persistence
- load save file and mark completed levels as done

### Reference from Kingdom Rush

![image](https://user-images.githubusercontent.com/6860637/94970438-f26a6880-0504-11eb-9b1c-3f0017a759fc.png)

Video reference: https://youtu.be/kHcO2NFInuY?t=14

**Comment by ZsTiziano** [comment]
I could try to do this.

**Comment by davcri** [comment]
Pull request merged! Closing this issue https://github.com/crystal-bit/hacktoberfest-2020/pull/34
