### ISSUE TITLE
Update Game Design Document with main game flow mechanics

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#29]
We need to specify in the [gdd](https://github.com/crystal-bit/hacktoberfest-2020/blob/master/docs/gdd.md) some main game mechanics such as:

- What happens when an Enemy reaches the `BaseArea`/`HitArea` (HitArea is the name currently used in the Level1 scene)
- How the player gains money?
- Where the strategic points can be placed?
- Which input peripherals should the game support?
- Should the towers be destroyable by the player? (eg: remove a tower to place another tower type) 
- probably other stuff too...

**Comment by vittorio-del-bianco** [comment]
I'm start to working on it.

**Comment by davcri** [comment]
Done!
