### ISSUE TITLE
Create a layer for the UI with a money & hp counter, pause button

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#32]
Note that in `game.gd` we already have a variable to keep track of player's money.

Reference image from Kingdom Rush (feel free to experiment with different layouts if you want):

![image](https://user-images.githubusercontent.com/6860637/95384943-9b420a80-08ed-11eb-88fc-2650b0d2d243.png)

Future work:

- wave gui indicator

**Comment by veonazzo** [comment]
I'll do this issue ;)

**Comment by davcri** [comment]
I pushed some assets on master that I found online! https://github.com/crystal-bit/hacktoberfest-2020/commit/442b6eb220de2e26f10c31f1bdb0eaf3da89972f

If @veonazzo doesn't have time to finish this issue, I'll take it on the next wednesday  probably :)

**Comment by davcri** [comment]
Done with https://github.com/crystal-bit/hacktoberfest-2020/commit/1210932cbca1fe57b02ce513343d733074e754bf
