### ISSUE TITLE
Add descriptions to Tower_Resource

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#33]
Tower_Resource does not have a description property.  
- [ ] Add the property and update the existing resources with some description
- [ ] Update `strategic-point.gd : _on_slot_activated` to use the new description property, so that the popup will be initialized correctly

Remember to take inspiration from what we currently have in the [GDD](https://github.com/crystal-bit/hacktoberfest-2020/blob/master/docs/gdd.md).

@vittorio-del-bianco if you have some ideas for the descriptions feel free to write them here!

**Comment by vittorio-del-bianco** [comment]
Ok @davcri , i try to help. :-)

Imho, a good starting point could be the strengths and weaknesses of each tower expressed in their respective sections (**_Good_** and **_Bad_**).
Moreover, keep this in mind: 

- **Bunkers** are base towers, filled with brave soldiers, who shoots enemies with their assault rifles and smoke grenades (smoke grenades applies slow effect on non-flying enemy units).

- **_Missile Towers_** are very destructive towers, fire explosive devices that deal area damage, and are technologically very advanced.

- **_Sniper Towers_** are masters of distance precision, manned by lethal snipers with large caliber weapons.

**Comment by m0rp30** [comment]
if free, I could do it.
