### ISSUE TITLE
Create battle music theme

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#37]
We need at least one music battle theme to be played during the gameplay scene.  

The game's theme will be military, read the [game design document](https://github.com/crystal-bit/hacktoberfest-2020/blob/master/docs/gdd.md) for more info.

**Comment by mRuggi** [comment]
I would like to contribute on this one

**Comment by mRuggi** [comment]
#47 
Planning to add some piano bass for the initial part and some fade out effect in order to loop it while the game plays
