### ISSUE TITLE
Create StrategicPoint scene

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#4]
A **StrategicPoint** is a point where the the player can build a tower. It is detailed in this screenshot taken from Kingdom Rush:

![image](https://user-images.githubusercontent.com/6860637/94724618-db881280-035a-11eb-961f-f69898c048c9.png)

Video gameplay here: https://youtu.be/kHcO2NFInuY

Requirements:

- [ ] Create a StrategicPoint scene
- [ ] It should open the `StrategicPointMenu` on pressing an activation area
- [ ] It should hide the `StrategicPointMenu` on pressing outside an activation area

**Comment by Sop-S** [comment]
I will implement this.
