### ISSUE TITLE
Update SlotButton to show a "Buy" image

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#41]
We need a more explicit way to show how to buy a tower.
We currently have a white decoration that is not really intuitive. We could use a texture with an icon and/or a "Buy" text.

![image](https://user-images.githubusercontent.com/6860637/95658785-497fc700-0b1d-11eb-9fbc-094eb8201fbd.png)

![image](https://user-images.githubusercontent.com/6860637/95658787-4dabe480-0b1d-11eb-80d0-b6fbc54531bd.png)

In Kigndom Rush is handled in this way:

![image](https://user-images.githubusercontent.com/6860637/95658750-fdcd1d80-0b1c-11eb-89f6-b646c6c7975a.png)

![image](https://user-images.githubusercontent.com/6860637/95658746-f60d7900-0b1c-11eb-9a2e-1e83b3f70512.png)

**Comment by ZsTiziano** [comment]
if free, I could do it.

**Comment by davcri** [comment]
@ZsTiziano I merged #48. However I think we can still improve the slot button when it's selected, so I'm gonna leave this issue open!
