### ISSUE TITLE
Add a graphical feedback for the press state in the credits scene

### ISSUE THREAD

**Issue by Andrea1141** [crystal-bit/hacktoberfest-2020#42]
I would add a circular texture progress as @davcri asked in #38.

**Comment by davcri** [comment]
@Andrea1141 thanks for opening the issue!  
I assigned it to you, if you don't want it or you cannot take it then you can remove it.

**Comment by Andrea1141** [comment]
Yes, I will do it. Thank you very much!

**Comment by Andrea1141** [comment]
#46 Solved! I added some white textures, so if someone wants to change the TextureProgress' colors can do it without problems.

**Comment by davcri** [comment]
@Andrea1141 I'm closing this issue, thanks! For the colors: we are going to wait the final design for the game.
