### ISSUE TITLE
Create StrategicPointMenu scene

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#5]
A **StrategicPointMenu** is the menu opened by pressing on a **StrategicPoint** (see #4).

![image](https://user-images.githubusercontent.com/6860637/94724618-db881280-035a-11eb-961f-f69898c048c9.png)

Video gameplay here: https://youtu.be/kHcO2NFInuY

Requirements:

- [x] Create a `StrategicPointMenu` scene
- [x] It should have multiple interactive **slots** (it's okay to have 4 slots like Kingdom Rush. Currently we still have to decide how many tower types we will support)
    - [x] each **slot** should show an icon and tower cost

Slot logic will be handled in another issue.

**Comment by Sop-S** [comment]
I will try to implement this issue.

**Comment by davcri** [comment]
Hi @Sop-S, thanks for your help. If you have any doubt feel free to ask on the Discord server!
