### ISSUE TITLE
Add enemy detection to Tower

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#55]
Add enemy detection logic to the Tower:

1. the tower should detect objects (enemies) that are inside the **Attack Range**
2. once an enemy enters the **Attack Range**, the tower should change state to something like `ATTACKING` and it should save the target enemy in a variable
3. once the `ATTACKING` state is started, a timer should be started as well to call a `fire` method periodically according to the tower's rate of fire

The fire method is optional, we can do it in another issue.

note: Enemies are going to extend the `Enemy` class which is a `KinematicBody2d`. I'm working on Enemies in #28. However this can be tested even without the enemy scene itself.

**Comment by Andrea1141** [comment]
I can do this issue.

**Comment by davcri** [comment]
Thanks @Andrea1141, I assigned the issue to you!
