### ISSUE TITLE
Implement enemy waves logic

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#56]
This depends on #28.

Each level needs data about enemy waves.  
See gdd for reference: https://github.com/crystal-bit/hacktoberfest-2020/blob/master/docs/gdd.md#enemy-waves

For now it's okay to just work on level1, but keep in mind that the code will need to be extended for the other levels.

**Comment by vittorio-del-bianco** [comment]
I'll try this.
