### ISSUE TITLE
Add "call enemy wave" button

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#57]
![image](https://user-images.githubusercontent.com/6860637/96183789-b937ec80-0f37-11eb-90e9-b43e0cd175d5.png)

This depends on #56.

Add an interactive widget to call the next wave.

**Comment by masmartyg** [comment]
I'd like to try to solve this issue if anyone else isn't interested. I don't know if I will be able to complete the task but I promise to commit myself.

**Comment by davcri** [comment]
Sure @masmartyg! If you have any doubt feel free to ask!
