### ISSUE TITLE
Add missing properties to Enemy resource

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#58]
Add missing stats to the [enemy resource](https://github.com/crystal-bit/hacktoberfest-2020/blob/master/scenes/enemy/enemy_resource.gd).

- add properties like `hp`, `armor`, `regen`, `speed`, `damage`, `money dropped`.
See the [game design document](https://github.com/crystal-bit/hacktoberfest-2020/blob/master/docs/gdd.md#enemies) for more info.
- add update the specific enemies' resources (see [enemy/enemy-types/](https://github.com/crystal-bit/hacktoberfest-2020/tree/master/scenes/enemy/enemy-types))
- [optional] update missing enemy textures. Feel free to open a new issue if you need new assets

**Comment by mRuggi** [comment]
Done in #67
