### ISSUE TITLE
Create TowerDescription popup element

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#6]
A **TowerDescription** is a popup menu that appears when a slot of **StrategicPointMenu** is pressed (see #5).

![image](https://user-images.githubusercontent.com/6860637/94727413-fbb9d080-035e-11eb-80b3-2b163114de70.png)

Requirements:

- [ ] Create a TowerDescription scene
- [ ] It should show Tower data (Name, Description, Speed, Attack Power)

#### Future work
We will need to check the spawn position of the TowerDescription popup to make sure that there is enough space to show all of its  content. Should we set a max width and height for this element?

**Comment by Karbb** [comment]
I will do it!

**Comment by davcri** [comment]
Almost done, we encountered some issues with the positioning and the resizing of the scene but we can handle this in another life, ehm issue.
