### ISSUE TITLE
Tower and Enemy resources lose the Texture property on import

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#60]
### Steps to reproduce:

1. Clone the repo `git clone https://github.com/crystal-bit/hacktoberfest-2020.git`
2. Open with Godot (it will import all the assets)
3. Open a Tower or Enemy resource in the inspector

**Expected result:**
Tower and Enemy resources load the correct textures as specified in the _import_ files. 

Eg: [scenes/tower/tower_types/sniper_1.tres](https://github.com/crystal-bit/hacktoberfest-2020/blob/master/scenes/tower/tower_types/sniper_1.tres) should load `"res://assets/sprites/tower-defense-top-down/png/tower-defense_tile249.png"`

**Current behaviour:**
Tower and Enemy resources lose the texture references.

![image](https://user-images.githubusercontent.com/6860637/96302304-e26c8180-0ff8-11eb-9cc3-00a81c247a04.png)

This is confirmed as well looking at the git status:

![image](https://user-images.githubusercontent.com/6860637/96302377-0039e680-0ff9-11eb-96ad-22152c9ef652.png)

**Note**
If, after importing all the assets, you close Godot and reset the repository using `git reset --hard` and you open again the project, the issue is fixed and the resources are in place.

**Comment by davcri** [comment]
I found a workaround https://github.com/crystal-bit/hacktoberfest-2020/commit/9eba5c30335ec835de5f14d760869b1376657eb4

It seems that this problem happens when loading resources before the actual files are imported by Godot.

Related issues:

- https://github.com/godotengine/godot/pull/36417

**Comment by ZsTiziano** [comment]
I think this is normal. 
if you don't want it, you also need to include the ".include" folder on git.

Error on Godot:
ERROR: _load: Resource loading failed: res: //.import/tower-defense_tile249.png-021981807620cbc1dc417901a4304418.stex. Make sure the assets have been imported by opening the project in the editor at least once.

this is unique "res: //.import/tower-defense_tile249.png-021981807620cbc1dc417901a4304418.stex"

**Comment by davcri** [comment]
It should be fixed on `master` now, we used an alternative usage for Tower and Enemy resources.

@ZsTiziano I don't think this was the normal behaviour, since it happens only when loading resources from a tool script.
