### ISSUE TITLE
Add logic to StrategicPointMenu slots

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#7]
After #5 is done, we need to add slot logic:

- [x] when a **slot** is pressed:
   - [x] it should open a `TowerDescription` popup menu
   - [x] it should change the state of the pressed slot. Graphically it should highlight or change the slot texture.
- [ ] when a **slot** is pressed and it's highlighted and the user has enough money to buy the tower:
   - [ ] it should dispatch a signal (eg: `tower_selected`).

**Comment by Gaarco** [comment]
I'll work on this
