### ISSUE TITLE
Add a "bodies in range" array in the tower script

### ISSUE THREAD

**Issue by Andrea1141** [crystal-bit/hacktoberfest-2020#70]
I would add an array to preserve all the bodies in the tower's range. It can be useful for adding a tower that can shoot multiple enemies and for resolving many bugs, for example if an enemy is faster than another. Since it is easy to implement, I can do this issue with another one.

**Comment by davcri** [comment]
Ok @Andrea1141 good idea! I'm assigning the issue to you then, ok?

Just a note: this array should be updated also when an enemy will die, but currently we cant' test this. Probably we will need to test it again after #71 and #72 .

**Comment by Andrea1141** [comment]
Perfect! I will work to this issue tomorrow!
