### ISSUE TITLE
Implement Tower.fire() method

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#71]
Implement `Tower.fire()` method: https://github.com/crystal-bit/hacktoberfest-2020/blob/master/scenes/tower/tower.gd#L112

Towers already detect enemies in range. We need the towers to fire missiles/bullets to enemies.  
Dealing HP damage will be implemented in another issue.

**Comment by Iranon** [comment]
Getting into the code at this point is a bit unhandy for me but I would like to handle this issue. I think I can have fun doing the missle/bullet scene. If I will be unable to do this before the end of the week I will report it.
