### ISSUE TITLE
Create HP bar for enemies

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#72]
Create an HP bar for the enemy scene.

Something like:
![image](https://user-images.githubusercontent.com/6860637/96625040-eb699580-130d-11eb-8d80-8bd98b7b2b85.png)

This will be used to show enemy's hp after #71 is implemented.

**Comment by Andrea1141** [comment]
I think I can do it, this and #70 are easy to implement. Can I create only a PR or is it a problem?

**Comment by davcri** [comment]
Sure, thanks @Andrea1141 !
