### ISSUE TITLE
Fix z-order of enemy HP bars

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#79]
![image](https://user-images.githubusercontent.com/6860637/96930387-e6e2df80-14bb-11eb-9376-b3d66163fc02.png)

**Comment by vclayton** [comment]
I can work on this. The goal is to have the health bars appear on top of the enemy sprites, right? I noticed there are bushes on the level that the enemies walk under. Should the progress bar be over or under those? I'm thinking over, but let me know if that's not right.

**Comment by davcri** [comment]
@vclayton thanks for taking this issue!  
I would say that the progress bar should be over the bushes and other level elements.
