### ISSUE TITLE
Create title image for main menu

### ISSUE THREAD

**Issue by davcri** [crystal-bit/hacktoberfest-2020#96]
@masmartyg did something already! I don't know if he wants to do that.

![image](https://user-images.githubusercontent.com/6860637/97359008-64339900-189c-11eb-995e-96a0bf2c2f5c.png)

**Comment by masmartyg** [comment]
I did other tests but I'm not happy with the result and I don't have much more time to dedicate to it, so for now I take this issue and send the PR of what I did. If someone wants to add / modify / replace ..

**Comment by davcri** [comment]
@masmartyg I merged your PR. I would like to add a vignette effect on the main menu, what do you think?

![image](https://user-images.githubusercontent.com/6860637/97628905-a3452400-1a2d-11eb-8b1e-1d13e03979b1.png)

**Comment by masmartyg** [comment]
Yeah, I like it 👍
